# Generated by Django 5.2.17 on 2026-09-30 16:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_evento', models.DateTimeField(verbose_name='Fecha y hora')),
                ('lugar', models.CharField(max_length=150, verbose_name='Lugar')),
                ('cupos', models.PositiveIntegerField(default=0, verbose_name='Cupos')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='Ruta de imagen (static)')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'eventos',
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Tipo de Novedad')),
            ],
            options={
                'verbose_name': 'Tipo de Novedad',
                'verbose_name_plural': 'Tipos de Novedad',
                'db_table': 'tipos_novedad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('resumen', models.TextField(verbose_name='Resumen')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='Ruta de imagen (static)')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades', to='inventarioApp.producto', verbose_name='Producto relacionado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='novedades', to='novedadesApp.tiponovedad', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'db_table': 'novedades',
                'ordering': ['-fecha'],
            },
        ),
    ]
